name: Array · NGINX · Deploy
on:
  push:
    branches: [main]
    paths:
      ["servers/array/nginx/**", ".github/workflows/array_nginx_deploy.yml"]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: "servers/array/nginx/"
      - name: Build Image
        run: docker build --tag "toolbi_array_nginx:1.0" ./servers/array/nginx/
      - name: Save Image
        run: docker save -o toolbi_array_nginx.tar toolbi_array_nginx:1.0
      - name: Send Image to the Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.SSH_ARRAY_HOST}}
          port: ${{secrets.SSH_ARRAY_PORT}}
          username: ${{secrets.SSH_ARRAY_USER}}
          key: ${{secrets.SSH_ARRAY_KEY}}
          source: "toolbi_array_nginx.tar"
          target: "/opt/images/"
      - name: Setup Deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_ARRAY_HOST}}
          port: ${{secrets.SSH_ARRAY_PORT}}
          username: ${{secrets.SSH_ARRAY_USER}}
          key: ${{secrets.SSH_ARRAY_KEY}}
          script: |
            mkdir -p /opt/deployments/toolbi_array_nginx
            docker kill toolbi_array_nginx
            cd /opt/deployments/toolbi_array_nginx/
            docker compose down
            docker load -i /opt/images/toolbi_array_nginx.tar
            rm /opt/images/toolbi_array_nginx.tar
      - name: "Send 'docker-compose.yml' to the Server"
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.SSH_ARRAY_HOST}}
          port: ${{secrets.SSH_ARRAY_PORT}}
          username: ${{secrets.SSH_ARRAY_USER}}
          key: ${{secrets.SSH_ARRAY_KEY}}
          source: "./servers/array/nginx/docker-compose.yml"
          target: "/opt/deployments/toolbi_array_nginx/"
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_ARRAY_HOST}}
          port: ${{secrets.SSH_ARRAY_PORT}}
          username: ${{secrets.SSH_ARRAY_USER}}
          key: ${{secrets.SSH_ARRAY_KEY}}
          script: |
            cd /opt/deployments/toolbi_array_nginx/
            docker compose up -d
